apiVersion: v1
kind: Pod
metadata:
  name: devops-demo-pod
  labels:
    app: devops-demo
    tier: frontend
  namespace: devops-workloads
spec:
  containers:
  - name: nginx
    image: nginx:1.27-alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
