apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  restartPolicy: Never
  containers:
  - name: demo
    image: busybox:1.37
    command:
    - sh
    - -c
    - echo coursework > /lab/proof.txt; sleep 3600
    volumeMounts:
    - name: data
      mountPath: /lab
  volumes:
  - name: data
    hostPath:
      path: /tmp/devops-coursework-volume
      type: DirectoryOrCreate
