apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-static-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: devops-static
  hostPath:
    path: /tmp/devops-coursework-pv
    type: DirectoryOrCreate
