apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: devops-static
  volumeName: devops-static-pv
  resources:
    requests:
      storage: 256Mi
