apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-lab-ingress
spec:
  podSelector:
    matchLabels:
      app: trouble-network
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 80
