apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
  namespace: devops-services
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - name: http
    port: 9090
    targetPort: http
