apiVersion: v1
kind: Service
metadata:
  name: webapp-headless
  namespace: devops-services
spec:
  clusterIP: None
  selector:
    app: webapp
  ports:
  - name: http
    port: 9090
    targetPort: http
