apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green
      track: green
  template:
    metadata:
      labels:
        app: blue-green
        track: green
    spec:
      containers:
      - name: web
        image: nginx:alpine
        command:
        - sh
        - -c
        - echo green > /usr/share/nginx/html/index.html; exec nginx -g "daemon off;"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 20m
            memory: 24Mi
          limits:
            cpu: 100m
            memory: 64Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 2
