apiVersion: v1
kind: Namespace
metadata:
  name: devops-gitops
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: coursework
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/suhaniawasthi10/devOps.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: devops-gitops
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - {group: '', kind: ConfigMap}
    - {group: '', kind: Secret}
    - {group: '', kind: Service}
    - {group: '', kind: PersistentVolumeClaim}
    - {group: apps, kind: Deployment}
    - {group: autoscaling, kind: HorizontalPodAutoscaler}
    - {group: networking.k8s.io, kind: Ingress}
