apiVersion: apps/v1
kind: Deployment
metadata:
  name: trouble-crash-loop
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: trouble-crash-loop
      track: trouble-crash-loop
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: web
        image: nginx:alpine
        command:
        - nginx
        - -g
        - daemon off;
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 20m
            memory: 24Mi
          limits:
            cpu: 100m
            memory: 64Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: trouble-crash-loop
spec:
  selector:
    app: trouble-crash-loop
  ports:
  - name: http
    port: 80
    targetPort: 80
